### ISSUE TITLE
Duplicate methods in Voxelmodell.cs are causing errors/incoherency 

### ISSUE THREAD

**Issue by Eharez** [Aitur/Bahnplanung-3D-Drucken-mit-Industrierobotern#5]
Infillmustererzeugen() und InsertInfill() sind Identisch

getNeighbors() sollte durch ist isNeighbor26 aus Voxel.cs ersetzbar sein, und ist abhängig von den Variablen des Typs: m_boundingBox_ welche ich gerne entfernen würde.

**Comment by Eharez** [comment]
neighbour?

**Comment by Aitur** [comment]
Gelöst
