### ISSUE TITLE
Insert Infill not working

### ISSUE THREAD

**Issue by Eharez** [Aitur/Bahnplanung-3D-Drucken-mit-Industrierobotern#7]
Die Methode InsertInfill() von Voxelmodell wirft eine  Invalid operation exception,
das liegt daran das sich das array auf dem der iterator läuft nicht verändern darf, solange dieser läuft.
Da aber im falle eines Nicht gesetzten Infill Voxels genau das passiert stürzt der code ab.

**Comment by Eharez** [comment]
Die gedoppelte Methode Infillmustererzeugen() würde im falle des Entfernens eine Voxels den nächsten Voxel nicht überprüfen, wirft aber nicht diese exeption.

**Comment by Aitur** [comment]
Zweite Methode gelöscht. Die eine Existente benutzt keinen Iterator mehr
